Make changes to support macOS.
wolfSSL/wolfEngine pull request #168
Opened 2021-11-16 22:53 UTC by haydenroche5

2021-11-17 02:17 UTC, ejohnstown reviewed
The script `openssl-unit-tests.sh` failed when running on an M1 Mac without Rosetta. It wasn't detecting the processor correctly, and v1.0.2 of OpenSSL doesn't seem to build for the M1 anyway. I forced Terminal to run through Rosetta, and it worked better, but still failed.

2021-11-18 20:25 UTC, haydenroche5 commented on scripts/openssl-unit-tests.sh
> +        echo "Not able to run tests on Mac with arm64 architecture, yet."
Coming soon. Need to resolve test failures with later OpenSSL 1.1.1 versions.

2021-11-19 00:40 UTC, ejohnstown requested changes

2021-11-19 00:40 UTC, ejohnstown commented on scripts/openssl-unit-tests.sh
> +    if [ "$OS" == "Darwin" ]; then
You don't have this check in the OpenSSL 1.1.1b case.

2021-11-19 18:07 UTC, ejohnstown approved these changes

2021-11-19 18:07 UTC, merged